# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :development_archive do
    gym(
        output_directory: 'IPA/',
        output_name: 'FastlaneDemo.ipa',
        scheme: 'FastlaneDemo',
        include_bitcode: true,
        configuration: 'Debug',
        export_method: "development",
    )
  end
  
  lane :release_archive do
    gym(
        output_directory: 'IPA/',
        output_name: 'FastlaneDemo.ipa',
        scheme: 'FastlaneDemo',
	clean: true,
        include_bitcode: true,
        configuration: 'Release',
        export_method: "app-store",
    )
  end

end
